export const StringConstants = {

    //async keys
    USER_ROLE: 'USER_ROLE',
    ACCESS_TOKEN: 'ACCESS_TOKEN',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REMEMBER_EMAIL: 'REMEMBER_EMAIL',
    REMEMBER_PASSWORD: 'REMEMBER_PASSWORD',


    WELCOME_TO_SPHIRI: 'Welcome to sphiri',
    SPHIRI_INTRO: 'Sphiri is an intelligent home management and family coordination platform designed to centralize all critical household information from vendor contacts and maintenance.',
    CHOOSE_YOUR_ROLE: 'Choose Your Role',
    WE_WILL_TAILOR_YOUR_EXPERIENCE: 'We will tailor your experience based on this selection.',
    HOMEOWNER: 'Homeowner',
    TRUSTEE: 'Trustee',
    VENDOR: 'Vendor',
    HOMEOWNER_DESC: 'Manage your own property and stay on top of tasks.',
    TRUSTEE_DESC: 'Oversee properties on behalf of others with clarity.',
    VENDOR_DESC: 'Offer services and collabrate with property owners.',
    SELECT: 'Select',
    LOGIN: 'Login',
    SIGN_UP: 'Signup',
    YOUR_DIGITAL_COMMAND_CENTER: 'Your digital command center for home management',
    EMAIL_ADDRESS: 'Email Address',
    PASSWORD: 'Password',
    FULL_NAME: 'Full Name',
    PHONE_NUMBER: 'Phone Number',
    CONFIRM_PASSWORD: 'Confirm Password',
    REMEMBER_ME: 'Remember me',
    FORGOT_PASSWORD: 'Forgot Password',
    DONT_HAVE_AN_ACCOUNT: 'Don\'t have an account?',
    ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',

    ENTER_FULL_NAME: 'Enter your full name',
    ENTER_EMAIL_ADDRESS: 'Enter your email address',
    ENTER_PHONE_NUMBER: 'Enter your phone number',
    ENTER_PASSWORD: 'Enter your password',
    ENTER_CONFIRM_PASSWORD: 'Enter your confirm password',
    FORGOT_YOUR_PASSWORD: 'Forgot your Password',
    FORGOT_YOUR_PASSWORD_DESC: 'Enter your email address to reset your password',
    VERIFY_EMAIL: 'Verify Email',
    CREATE_NEW_PASSWORD: 'Create New Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_NEW_PASSWORD: 'Confirm New Password',
    ENTER_NEW_PASSWORD: 'Enter New Password',
    ENTER_CONFIRM_NEW_PASSWORD: 'Confirm New Password',
    CONTINUE: 'Continue',


    //Home
    FAMILY_DASHBOARD: 'Family Dashboard',
    HOME_TITLE: `Here's what's happening with your home today`,
    TRUSTEE_TITLE: `Welcome back, Sarah Johnson. Here's an overview of shared household information`,
    CRITICAL_ALERTS: 'Critical Alerts',
    UPCOMING_REMINDERS: 'Upcoming Reminders',
    RECENT_ACTIVITY: 'Recent Activity',
    SMART_SUGGESTIONS: 'Smart Suggestions',
    EDITOR_ROLE: 'Editor Role',
    RESCHEDULE: 'Reschedule',
    COMPLETE: 'Complete',
    VIEW_ALL: 'View All',
    CONTACT_DIRECTORY: 'Contact Directory',
    CONTACT_DIRECTORY_DESC: 'Manage your vendors, family, and professional contacts',
    ADD_CONTACT: 'Add Contact',
    DOCUMENT_MANAGEMENT: 'Document Management',
    DOCUMENT_MANAGEMENT_DESC: 'Secure storage for all your important documents',
    UPLOAD_DOCUMENT: 'Upload Document',
    NEW_FOLDER: 'New Folder',
    REMINDER_AND_TASKS: 'Reminders & Tasks',
    ADD_REMINDER: 'Add Reminder',
    EXPORT_CALENDAR: 'Export Calendar',
    ADD_EVENT: 'Add Event',
    TASKS_AND_REMINDERS: 'Tasks & Reminders',
    CREATE_REMINDER: 'Create Reminder',
    MANAGE_YOUR_HOME: 'Manage your household tasks, maintenance schedules, and important reminders',
    SEARCH_REMINDERS: 'Search reminders...',
    THIS_WEEK_SCHEDULE: `This Week's Schedule`,
    MARK_COMPLETE: 'Mark Complete',
    SNOOZE: 'Snooze',
    FAMILY_SHARING_AND_COLLABORATION: 'Family Sharing & Collaboration',
    INVITE_MEMBER: 'Invite Member',
    MANAGE_FAMILY_MEMBERS_PERMISSIONS: 'Manage family members, permissions, and shared access.',
    MANAGE_FAMILY_ACCESS_AND_EMERGENCY_PROTOCOLS: 'Manage family access and emergency protocols',
    EMERGENCY_ACCESS_PROTOCOL: 'Emergency Access Protocol',
    CONFIGURE_EMERGENCY_ACCESS_PROTOCOL: 'Configure trusted contacts who can access critical information during emergencies or after prolonged inactivity.',
    CONFIGURE_EMERGENCY_ACCESS: 'Configure Emergency Access',
    VIEW_PROTOCOLS: 'View Protocols',
    FAMILY_MEMBERS: 'Family Members',
    SHARED_CONTENT_CONTROLS: 'Shared Content Controls',
    EMERGENCY_ACCESS_CONFIGURATION: 'Emergency Access Configuration',
    SET_UP_TRUSTED: 'Set up trusted contacts who can access your account during emergencies',
    ACCESS_DURATION: 'Access Duration',
    SAVE_EMERGENCY_SETTINGS: 'Save Emergency Settings',
    SETTINGS: 'Settings',
    MANAGE_YOUR_ACCOUNT: 'Manage your account preferences and security',
    CURRENT_PASSWORD: 'Current Password',
    ENTER_CURRENT_PASSWORD: 'Enter your current password',
    UPDATE_PASSWORD: 'Update Password',
    NOTIFICATION_PREFERENCES: 'Notification Preferences',
    CHOOSE_HOW_TO_NOTIFIED: 'Choose how you want to be notified about important updates',
    EMAIL_NOTIFICATIONS: 'Email Notifications',
    SMS_NOTIFICATIONS: 'SMS Notifications',
    PUSH_NOTIFICATIONS: 'Push Notifications',
    RECEIVED_VIA_EMAIL: 'Receive updates via email',
    RECEIVED_VIA_SMS: 'Receive text messages for critical alerts',
    RECEIVED_VIA_PUSH: 'Get push notifications on your devices',
    NOTIFICATION_CATEGORIES: 'Notification Categories',
    PROTOCOL_ACTIVITY: 'Protocol Activity',
    CONFIGURATION: 'Configuration',
    SHARED_DOCUMENTS: 'Shared Documents',
    UPCOMING_JOBS: 'Upcoming Jobs',
    VENDORS_AND_CONTACTS: 'Vendors & Contacts',


    //Modal
    CANCEL: 'Cancel',
    NEXT: 'Next',
    SAVE_CHANGES: 'Save Changes',
    PREVIOUS: 'Previous',
    CONTACT_DETAILS: 'Contact Details',
    EDIT_CONTACT: 'Edit Contact',
    BASIC_INFORMATION: 'Basic Information',
    CATEGORY: 'Category',
    VISIBILITY: 'Visibility',
    TAGS: 'Tags (comma separated)',
    NOTES: 'Notes',
    ADD_NEW_CONTACT: 'Add New Contact',
    UPLOAD: 'Upload',
    DOCUMENT_UPLOAD_LINE: 'Drag and drop files here, or click to browse',
    SUPPORT_FILES: 'Supports PDF, DOC, XLS, JPG, PNG (Max 10MB)',
    CREATE_NEW_REMINDER: 'Create New Reminder',

    //Trustee
    DOCUMENTS: 'Documents',
    DOCUMENTS_SHARED_WITH_YOUR_ROLE: 'documents shared with your role',
    DOCUMENT_CATEGORIES: 'Document Categories',
    RECENT_FILES: 'Recent Files',
    DOCUMENT_MANAGEMENT_EDITOR: 'As an editor, you can upload new versions of shared documents. All uploads are versioned and can be restored if needed.',
    UPLOAD_DOCUMENTS: 'Upload Documents',
    SERVICE_NAME: 'Service Name',
    SERVICE_DATE: 'Service Date',
    AMOUNT: 'Amount',
    SERVICE_NOTES: 'Service Notes',
    CLICK_TO_UPLOAD_DOCUMENTS: 'Click to upload documents',
    SUPPORT_FILES_TYPES: 'PDF, DOC, XLS (Max 10MB per file)',
    TAKE_PHOTO: 'Take Photo',
    CHOOSE_FROM_GALLERY: 'Choose from Gallery',
    UPLOAD_ALL: 'Upload All',
    CALENDER_SYNC: 'Calendar Sync',
    CALENDER_SYNC_DESC: 'All assigned reminders sync with your Google Calendar. Notifications are sent according to your preferences (email, SMS, push).',
    EMERGENCY_ACCESS: 'Emergency Access',
    RESTRICTED_ACCESS_TO_CRITICAL_INFORMATION: 'Restricted access to critical information',
    ACCESS_LOCKED: 'Access Locked',
    ACCESS_LOCKED_DESC: 'Emergency documents are restricted and require activation',
    LEGAL_AND_MEDICAL_DOCUMENTS: 'Legal & Medical Documents',
    HOW_THIS_WORKS: 'How This Works',
    EMERGENCY_ACCESS_WORKING: 'Emergency access is restricted to prevent unauthorized viewing of sensitive medical and legal documents. When activated, you will have 24-hour access to view critical information. The primary user will receive a notification of your request.',

    //Vendor
    COMPANY_INFORMATION: 'Company Information',
    TELL_US_ABOUT_YOUR_BUSINESS: 'Tell us about your business',
    COMPANY_NAME: 'Company Name',
    SERVICE_TYPE: 'Service Type',
    BUSINESS_PHONE: 'Business Phone',
    BUSINESS_ADDRESS: 'Business Address',
    COMPLETE_YOUR_PROFILE: 'Complete Your Profile',
    ENTER_COMPANY_NAME: 'Enter Company Name',
    ENTER_SERVICE_TYPE: 'Enter Service Type',
    ENTER_BUSINESS_PHONE: 'Enter Business Phone',
    ENTER_BUSINESS_ADDRESS: 'Enter Business Address here..',
    PROFESSIONAL_DOCUMENTS: 'Professional Documents',
    UPLOAD_YOUR_CERTIFICATES: 'Upload your certifications and licenses',
    BUSINESS_LICENSE: 'Business License',
    INSURANCE_CERTIFICATE: 'Insurance Certificate',
    PROFESSIONAL_CERTIFICATIONS: 'Professional Certifications',
    VERIFICATION_IN_PROGRESS: 'Verification In Progress',
    OUR_TEAM_WILL_REVIEW: 'Our team will review your documents within 24-48 hours',
    LIMITED_ACCESS_GRANTED: 'Limited Access Granted',
    YOU_CAN_EXPLORE: 'You can explore the app while we verify your documents',
    MY_CLIENTS: 'My Clients',
    SEARCH_CLIENTS: 'Search clients...',
    ANALYTICS: 'Analytics',
    MESSAGES: 'Messages',
    REVENUE_OVERVIEW: 'Revenue Overview',
    EDIT_PROPOSAL: 'Edit Proposal',
    NEW_PROPOSAL: 'New Proposal',
    CLIENT_NAME: 'Client Name',
    PROPOSAL_TITLE: 'Proposal Title',
    VALID_UNTIL: 'Valid Until',
    DESCRIPTION: 'Description',
    SCOPE_OF_WORK: 'Scope of Work',
    TERMS_AND_CONDITIONS: 'Terms & Conditions',
    PROPOSAL_DETAILS: 'Proposal Details',
    CLOSE: 'Close',
    DOWNLOAD_PDF: 'Download PDF',
    CREATED_DATE: 'Created Date',
    STATUS: 'Status',
    PROPOSAL_AMOUNT: 'Proposal Amount',
    VIEW_ALL_SERVICES: 'View All Services',
    SCHEDULE_SERVICE: 'Schedule Service',
    UPLOAD_NEW_DOCUMENT: 'Upload New Document',
    VIEW_ALL_MESSAGES: 'View All Messages',
    CREATE_PROPOSAL: 'Create Proposal',
    CREATE_INVOICE: 'Create Invoice',
    INVOICE_NUMBER: 'Invoice Number',
    DUE_DATE: 'Due Date',
    DEPOSIT_AMOUNT: 'Deposit Amount (Optional)',
    TOTAL_AMOUNT: 'Total Amount',
    SUBTOTAL: 'Subtotal',
    TAX: 'Tax',
    SCHEDULE: 'Schedule',
    ALL_APPOINTMENTS: 'All Appointments',
    APPOINTMENT_DETAILS: 'Appointment Details',
    START_SERVICE: 'Start Service',
    CANCEL_APPOINTMENT: 'Cancel Appointment',
    SEARCH_CONVERSATIONS: 'Search conversations...',
    TYPE_A_MESSAGE: 'Type a message...',

    PROFILE: 'Profile',
    TAG: 'Tags',
    CUSTOM_FIELDS: 'Custom Fields',
    ENGAGEMENT_HISTORY: 'Engagement History',
    LOG_ENGAGEMENT: 'Log Engagement',
    VIEW_INVOICE: 'View Invoice',
    ATTACHMENTS: 'Attachments',
    SAVE_NOTE: 'Save Note',
    LIST_VIEW: 'List View',
    CALENDAR_VIEW: 'Calendar View',
    PROFILE_HOME_OWNER: 'Update your personal information and profile details.',
    PROFILE_TRUSTEE: 'Manage your family member profile and informations',
    ADD_CLIENT: 'Add Client'





};