export const ApiConstants = {
    //AUTH
    BASE_URL: 'http://168.231.121.7/sphiri/api/',
    MEDIA_URL: 'http://168.231.121.7',
    LOGIN: 'auth/mobile/login/',
    SIGNUP: 'auth/signup/',
    VENDOR_ONBOARDING_STEP_ONE: 'vendor-onboarding/step-1/',
    VENDOR_ONBOARDING_STEP_TWO: 'vendor-onboarding/step-2/',
    VENDOR_ONBOARDING_STEP_THREE: 'vendor-onboarding/step-3/',
    VENDOR_ONBOARDING_REVIEW: 'vendor-onboarding/review/',
    FORGOT_PASSWORD: 'auth/mobile/forgot-password/',
    RESET_PASSWORD: 'auth/mobile/reset-password/',
    CHANGE_PASSWORD: 'profile/change-password/',
    SETUP_2FA: 'auth/2fa/setup/',
    DELETE_ACCOUNT: 'auth/delete-account/',

    //PROFILE
    GET_PROFILE: 'settings/profile/',
    UPLOAD_PROFILE_IMAGE: 'profile/picture/',
    PROFILE_NOTIFICATIONS: 'profile/notifications/',
    SETTINGS_NOTIFICATIONS: 'settings/notifications/',
    SETTINGS_BILLING: 'settings/billing/',
    SETTINGS_BACKUP: 'settings/backup/',
    FAMILY_MEMBERSDHASBOARD: 'family-member/dashboard/',
    SHARE_CONTACTS: 'family-member/shared-contacts/',
    SHARE_DOCUMENTS: 'family-member/shared-documents/',
    SHARED_DOCUMENTS_LIST: 'family-member/shared-documents/',
    SHARED_FOLDERS: 'family-member/shared-folders/',
    SHARED_REMINDERS: 'family-member/shared-reminders/',
    SHARED_REMINDERS_CALENDAR: 'family-member/shared-reminders/calendar/',
    SHARED_REMINDER_DETAILS: 'family-member/shared-reminders/',
    FAMILY_MEMBER_SETTINGS: 'family-member/settings/',
    FAMILY_MEMBER_PROFILE: 'family-member/profile/',
    FAMILY_MEMBER_MOVING_CHECKLIST: 'family-member/moving-checklist/',
    VENDOR_DASHBOARD: 'vendor-panel/dashboard/',
    VENDOR_CLIENTS: 'vendor-panel/clients/',
    VENDOR_CLIENT_SERVICES: 'vendor-panel/clients/', // Used as VENDOR_CLIENT_SERVICES + id + '/services/'
    VENDOR_CLIENT_DOCUMENTS: 'vendor-panel/clients/', // Used as VENDOR_CLIENT_DOCUMENTS + id + '/documents/'
    VENDOR_CLIENT_NOTES: 'vendor-panel/clients/', // Used as VENDOR_CLIENT_NOTES + id + '/notes/'
    VENDOR_CLIENT_REMINDERS: 'vendor-panel/clients/', // Used as VENDOR_CLIENT_REMINDERS + id + '/reminders/'
    VENDOR_DOCUMENTS: 'vendor-panel/documents/',
    VENDOR_NOTES: 'vendor-panel/notes/',

    //PERMISSIONS
    VENDOR_PERMISSIONS: 'vendor-panel/permissions/',
    VENDOR_PERMISSIONS_COMPLIANCE: 'vendor-panel/permissions/compliance/',
    VENDOR_PERMISSIONS_SECURITY_POLICIES: 'vendor-panel/permissions/security-policies/',

    //VENDOR ANALYTICS
    VENDOR_ANALYTICS: 'vendor-panel/analytics/',
    VENDOR_ANALYTICS_RENEWAL_PIPELINE: 'vendor-panel/analytics/renewal-pipeline/',
    VENDOR_ANALYTICS_FEEDBACK: 'vendor-panel/analytics/feedback/',
    VENDOR_PROFILE: 'vendor-panel/profile/',

    DASHBOARD_HOME_OWNER: 'dashboard/home-owner/',
    VENDOR_CATEGORIES: 'vendor-categories/',
    VENDOR_TAGS: 'vendor-tags/',
    VENDORS_LIST_CONTACTS: 'vendors/',
    VISIBILITY_OPTIONS: 'vendor-visibility-options/',
    VENDORS_CREATE: 'vendors/create/',
    VENDORS_ENGAGEMENTS: '/engagements/',
    VENDORS_ATTACHMENTS: '/attachments/',
    VENDORS_NOTES: '/notes/',
    REMINDERS: 'reminders/',
    DELETE_REMINDER: 'reminders/delete-reminder/',
    EDIT_REMINDER: 'reminders/edit-reminder/',
    REMINDERS_STATS: 'reminders/dashboard-stats/',
    TODOS: 'reminders/todos/',
    SNOOZE_REMINDER: 'reminders/snooze-reminder/',
    HOMEOWNER_DOCUMENTS: 'documents/', // Used for details (id/), versions (id/versions/), and legacy access (id/legacy-access/)
    HOMEOWNER_DOCUMENT_CATEGORIES: 'documents/categories/',
    MEMBERS: 'members/',
    MEMBERS_ACTIVITY: 'members/activity/',
    PLANS: 'plans/',
    HOME_INVENTORY: 'home-inventory/',
    HOME_INVENTORY_CATEGORIES: 'home-inventory/categories/',
    VENDOR_MESSAGES: 'vendor-panel/messages/',
    VENDOR_NOTIFICATIONS_API: 'vendor-panel/profile/notifications/',
    PUSH_NOTIFICATIONS_API: 'notifications/push/',
    INVITES_API: 'invites/',
    VENDOR_NOTIFICATION_READ: 'vendor-panel/profile/notifications/',
    VENDOR_NOTIFICATION_MARK_ALL_READ: 'vendor-panel/profile/notifications/mark-all-read/',
    HOMEOWNER_NOTIFICATION_READ: 'notifications/push/',
    HOMEOWNER_NOTIFICATION_MARK_ALL_READ: 'notifications/push/mark-all-read/',
    EMERGENCY_ACCESS_FAMILY_MEMBER: 'family-member/emergency-access/',
    FAMILY_MEMBER_PROFILE_PICTURE: 'family-member/profile/picture/',
    MEMBER_EMERGENCY_ACCESS: '/emergency-access/', // Used as MEMBERS + id + MEMBER_EMERGENCY_ACCESS
    ACCEPT_INVITE: '/accept/', // Used as SHOW_INVITE + id + ACCEPT_INVITE
    REJECT_INVITE: '/reject/', // Used as SHOW_INVITE + id + REJECT_INVITE
    SHOW_INVITE: 'invites/',
    DOWNLOAD_AUDIT: 'family-member/settings/audit/download/',
    VENDOR_PROPOSALS: 'vendor-proposals/',
    HOMEOWNER_MESSAGES: 'homeowner-panel/messages/',
    LIST_OF_VENDORS: 'homeowner-panel/messages/vendors/',
    START_CONVERSATION: 'homeowner-panel/messages/start/',
    LINKED_CONTACTS: 'documents/linked-contacts/',

    GROW_BUSINESS: 'vendor-panel/grow-business/',
    SUPPORT_TICKETS: 'support/tickets/',
    RAISE_TICKET: 'support/tickets/raise-ticket/',
    REPLY_TICKET: '/reply/',
    ADD_PAYMENT_METHODS: 'settings/billing/payment-methods/',
    UNREAD_COUNT: 'notifications/push/unread-count/', //this api is not in use now
    FORM_OPTIONS: 'reminders/form-options/',
    PROPERTIES: 'properties/',
    EMERGENCY_ACCESS: 'settings/emergency-access/',
    DEACTIVATE_EMERYGENCY_ACCESS: 'settings/emergency-access/deactivate/',
    MY_FOLDERS_LIST: 'documents/my-folders/',
    DEFAULT_CATEGORIES: 'documents/default-categories/',
    VENDOR_PROFESSIONAL_CATEGORIES_SEED: 'vendor-professional-categories/seed/',
    AVAILABLE_FAMILY_MEMBERS: 'assignments/available-family-members/',
    VENDOR_ASSIGNMENTS: 'vendor-assignments/',
    CREATE_PERSONAL_CONTACT: 'personal-contacts/create/',
    PERSONAL_CONTACTS_LIST: 'personal-contacts/',
    DOCUMENT_TAGS: 'documents/tags/',
    VENDOR_HOME_INVENTORY: 'vendor-panel/home-inventory/',
    VENDOR_REMINDERS_API: 'vendor-panel/reminders/',
    TOOLS_REPORTS_GENERATE: 'tools/reports/generate/',
    CONTACT_TAGS: 'contact-tags/',
    GLOBAL_TAG_GROUPS: 'contact-tags/groups/',
    MAINTENANCE_PLANNER: 'tools/workflows/maintenance-planner/',
    EMERGENCY_HOME_FILES: 'tools/workflows/emergency-home-file/',
    INSURANCE_INVENTORY: 'tools/workflows/insurance-inventory/',
    MOVING_PLANNER: 'tools/workflows/moving-planner/',
    ESTATE_PREPARATION: 'tools/workflows/estate-preparation/',
    GENERATE_PDF: 'tools/workflows/generate-pdf/',

};
